package com.akshatha.spring.email;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Component;

import com.akshatha.spring.entity.SignUp.SignUpEntity;
import com.akshatha.spring.util.EncryptDecryptString;

@Component
public class MailSendingImpl implements MailSending {

	@Autowired
	private JavaMailSender mailSender;

	@Autowired
	private SimpleMailMessage mailMessage;

	@Autowired
	private EncryptDecryptString encryptDecrypt;

	public void sendingEmail(SignUpEntity datafromentity) {
		try {
			mailMessage.setTo(datafromentity.getUserEmail());
			mailMessage.setSubject("Signup Confirmation ");
			mailMessage.setText("Hi," + datafromentity.getUserName() + " "
					+ "You have Successfully completed Signup Process Here is link to Change the password.Use AutoGenerated password  and Username to change the password"
					+" "+"UserName"+ " " + datafromentity.getUserName() + " " +"Password"+" "
					+ encryptDecrypt.decrypt(datafromentity.getPassword())+ " "
					+ "click on the Link" + " " + "http://localhost:8080/SecurePassword/changePassword?userName="
					+ datafromentity.getUserName());
			mailSender.send(mailMessage);
			System.out.println("Mail sent for user");
		} catch (Exception e) {
			System.err.print("Exception occured : \t" + e);
		}

		
	}
}
